### ISSUE TITLE
카카오맵 로딩 문제

### ISSUE THREAD

**Issue by hjiwon** [Step3-kakao-tech-campus/Team16_FE#171]
![image](https://github.com/Step3-kakao-tech-campus/Team16_FE/assets/77186082/845e834e-4785-44d2-8198-e5d9a48bc5d1)
위의 사진에서 주황색이 전부 카카오맵 api 호출 관련 부분입니다.
현재 로딩에 오랜 시간이 걸리는 문제가 있습니다.

홈 페이지, 펫 상세조회 페이지 등에서도 간헐적으로!! 지도를 불러오고 있습니다.
문제가 생길 때마다 15000~20000ms 가량 걸려서 개선이 필요합니다.

**Comment by JeonDoGyun** [comment]
이거는 닫도록 하겠습니다!
