### ISSUE TITLE
각자가 구현한 페이지 or 기능에 대한 설명 ❗금요일 밤 10시까지❗

### ISSUE THREAD

**Issue by JeonDoGyun** [Step3-kakao-tech-campus/Team16_FE#175]
## 각 트랙별 코딩에 대한 간략한 설명 ❗금요일 밤 10시까지❗
- 그동안 피드백 해주신 멘토님이 아닌, 다른 조의 멘토님이 공정성을 위해 평가에 같이 참여합니다.
- 따라서 쿠키즈가 주안점을 두고 개발한 기능이 무엇인지, 서비스를 기획하게 된 의도 등을 리드미에 작성해 주세요.

### Template
```
1. 구현한 페이지
2. 주요 기능
3. 구현하면서 신경 썼던 부분(코드)
```
### Guideline
```
- 지금까지 주 차별로 구현하면서 있었던 history를 코드 평가자가 알 수 있도록
- 어떤 의도를 가지고 코드를 작성했다. or 서비스를 기획했다.
```

**Comment by hjiwon** [comment]
1. 홈 화면, 등록하기와 수정하기 페이지의 사진 / 동영상 업로드, GNB, 내 주변 보호소 찾기, 상세정보 페이지

**Comment by LimSumi** [comment]
- 프로필리스트(홈, 긴급, 신규)
  - 주요기능
  유기동물의 사진과 간단한 정보를 리스트 형태로 보여준다.
  - 신경쓴 점
   비슷한 구성이 여러군데에서 나오는 부분이라서 컴포넌트 재사용을 위해 신경썼다.

- 보호소 프로필리스트
  - 주요기능
  보호소의 간단한 정보와 해당 보호소에서 관리중인 유기동물 리스트를 보여준다.
  로그인된 계정의 경우 본인 보호소 정보로 이동하면 유기동물 수정하기 버튼이 보인다.
  - 신경쓴 점
  반응형 ui 와 수정하기 버튼 처리 위치에 대해 고민하였다.

- 등록하기 상세정보 
  - 주요기능 
  등록하기의 상세 정보를 입력받을 수 있다.
  - 신경쓴점
  input 방식이 다른 값들을 모아서 autoComplete 값을 주는 방식을 많이 고민했다.

**Comment by JeonDoGyun** [comment]
> * 프로필리스트(홈, 긴급, 신규)

이거 홈이 어디 말하는건가요?
