### ISSUE TITLE
[FE] GitHub Actions로 빌드 및 실행, 테스트 확인, 배포 트리거 설정 추가

### ISSUE THREAD

**Issue by GreenNarae0** [Step3-kakao-tech-campus/Team16_FE#82]
## 목적

- 로컬에서 잘 실행되는 것이 우분투환경에서 실행되지 않거나, 로컬에서 실수로 실행되지 않는 코드를 Push할 경우를 대비해 GitHub Actions로 통합과 배포과정을 자동화 합니다.

**Comment by JeonDoGyun** [comment]
그럼 기존의 방식과 달라지는 부분은 어떤 건가요?? Github Actions를 잘 몰라서..

**Comment by GreenNarae0** [comment]
PR에 설명 추가했습니다!
